spring:
  application:
    name: api-controle-de-gastos

  datasource:
    url: jdbc:mysql://square-cloud-db-4939545f82b94cbd9901966148acdab8.squareweb.app:7007/db_controle_de_gastos_homologacao?sslMode=REQUIRED&serverTimezone=America/Sao_Paulo&characterEncoding=UTF-8
    username: squarecloud
    password: MOuCbMnoAwItHA5EEICSAGlt
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: 'SMTP_HOST.com'
    port: 500
    username: 'SMTP_USER'
    password: 'ffd'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

security:
  config:
    prefix: Bearer
    key: SECRET
    expiration: 3600000

jwt:
  secret: DDDFGFDSKKMMMMMMSAKALSMALDAGHGFJDLEEKEMDSSDADNFGBVVCC
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: 8081
  address: 0.0.0.0

photo-service:
  url: https://ms-imagem.squareweb.app
